<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Terms of Service</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	
	<style>
		body {width: 80%; margin-left: 10%}
		p {margin-left: 50px;}
	</style>

    <body>
        
<script type="text/javascript">
	var capterra_vkey = '648584582a6c3e1ffa8ccb7ea0e56529',
	capterra_vid = '2094153',
	capterra_prefix = (('https:' == document.location.protocol) ? 'https://ct.capterra.com' : 'http://ct.capterra.com');

	(function() {
	var ct = document.createElement('script'); ct.type = 'text/javascript'; ct.async = true;
	ct.src = capterra_prefix + '/capterra_tracker.js?vid=' + capterra_vid + '&vkey=' + capterra_vkey;
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ct, s);
	})();
</script>

<div id="policy" class="content">
	<div class="text">
		<h1>Minical Inc. Terms of Service</h1>
		<h3>1. Acceptance of Terms of Service</h3>
		<p>1.1. Welcome to the Minical Services, tools and software (collectively, the &quot;Minical Service&quot;), provided to you by Minical Inc.(&quot;we&quot;, &quot;us&quot;, &quot;our&quot;, or &quot;Minical&quot;).</p>

		<p>1.2. Your use of the Minical Service or Minical's Web properties through which the Minical Service is available is subject to this Minical Terms of Service (&quot;TOS&quot;) in effect at the time of your use. Minical reserves the right to update and change this TOS from time to time without notice or acceptance by you, so please check this page frequently for updates and changes. However, changes made to this TOS will not apply to you to the extent that (i) the changes concern matters which are the subject of an actual dispute between you and Minical as of the date the changes take effect and (ii) Minical has actual notice of the dispute as of the date the changes take effect.</p>
		<p>1.3. Your use of the Minical Service or Minical's Web properties through which the Minical Service is available is also subject to the Minical General Terms of Use (the &quot;Terms of Use&quot;) in effect at the time of your use, which are incorporated herein as though set forth in full. For the purposes of the Terms of Use, the Minical Service is a &quot;Service,&quot; any software that you download from Minical to implement the Minical Service is &quot;Software,&quot; any account you create to use the Minical Service is an &quot;Account&quot; and each of Minical's Web properties through which the Minical Service is available is a &quot;Site.&quot; In the event of any conflict between this TOS and the Terms of Use, this TOS will control. For the avoidance of doubt, if there are terms and conditions in the Terms of Use regarding subjects on which this TOS is silent, such silence will not constitute a conflict and the terms and conditions in the Terms of Use will control.</p>

		<p>1.4. Your use of the Minical Service or Minical's Web properties through which the Minical Service is available is also subject to the Minical Privacy Policy in effect at the time of your use, which is incorporated herein as though set forth in full. For the purposes of the Minical Privacy Policy, the Minical Service, any software that you download from Minical to implement any part of the Minical Service and Minical's Web properties through which the Minical Service is available, singly and in combination, constitute part of the &quot;Minical Sites, Products and Services.&quot; You can review the most current version of the Minical Privacy Policy <a href="https://demo.minical.io/auth/show_privacy_policy">here</a>.</p>
		<p>1.5. By signifying your acceptance of this TOS or making any use of the Minical Service, you signify your irrevocable acceptance of this TOS, the Terms of Use and the Minical Privacy Policy in effect at the time of your use. If you are an individual acting as a representative of a corporation or other legal entity which wishes to use the Minical Service, then you represent and agree that you have the authority to accept this TOS, the Terms of Use and the Minical Privacy Policy on behalf of such corporation or other legal entity and that all provisions of this TOS, the Terms of Use and the Minical Privacy Policy will bind that corporation or other legal entity as if it were named in this TOS, the Terms of Use and the Minical Privacy Policy in place of you.</p>
		<p>1.6. The Minical Service is not intended for users under the age of thirteen (13). By signifying your acceptance of this TOS or making any use of the Minical Service, you represent and warrant that you are at least thirteen (13) years of age.</p>
		
		<h3>2. Registration, Account Information and Security</h3>

		<p>2.1. When you register to use the Minical Service, you must provide true, accurate, current and complete information about yourself and maintain and promptly update your account information to keep it true, accurate, current and complete.</p>
		<p>2.2. You are responsible for maintaining control over access to your account, including the confidentiality of your account log-in and password, and are responsible for all activities that occur on or through your account, whether authorized by you or not. Minical will not be liable for any loss or damage arising from your failure to maintain control over access to your account.</p>
		
		<h3>3. Versions and Service Levels</h3>
		<p>3.1 The Minical Service may be made available in free or paid versions and/or in different service levels. Not all of the features and functionality of the Minical Service may be available in each version or service level. The features and functionality of each version or service level may be changed from time to time at Minical's discretion.</p>
		<p>3.2 Minical reserves the right to change, suspend or discontinue part or all of any version of the Minical Service at any time, for any reason, without notice and without explanation.</p>
		
		<h3>4. Professional Services</h3>

		<p>4.1. Minical may offer certain professional services, such as design, customization and marketing services, to users of the Minical Service (collectively, the &quot;Professional Services&quot;). If you desire to engage Minical to provide Professional Services, you and Minical will document the scope, cost, schedule and deliverables for each such Professional Services engagement in a separate Statement of Work to be executed by both parties. Each Statement of Work will be subject to all of the terms and conditions of this TOS. In the event of any conflict between this TOS and any Statement of Work, the terms of the Statement of Work will control.</p>
		<p>4.2. Minical will perform the Professional Services described in each Statement of Work in a competent and professional manner and will use its reasonable commercial efforts to cause the Professional Services to be completed according to the schedule set forth in the Statement of Work. You will provide all assistance and cooperation reasonably necessary to permit Minical to timely and efficiently provide the Professional Services. You acknowledge that Minical will not be in breach of any Statement of Work if Minical's failure to provide the Professional Services is caused by your failure to provide the necessary assistance and cooperation.</p>
		<p>4.3. Upon payment in full of all of Minical's invoiced fees for the Professional Services, you will have a worldwide, royalty-free, non-exclusive, non-transferable right and license to use the deliverables specified in the corresponding Statement of Work (the &quot;Deliverables&quot;) solely in connection with your Minical account. You will not rent, sell, assign, lease, sublicense or otherwise transfer any Deliverables.</p>
		<p>4.4. Minical owns all right, title and interest in and to the Deliverables. Minical reserves all rights to the Deliverables that are not expressly granted to you herein. Nothing herein will be construed as granting you any property rights in the Deliverables, or to any invention or any patent, copyright, trademark, or other intellectual property right that has been issued, or that may issue, based on the Deliverables. The Deliverables are licensed hereby, not sold.</p>

		<h3>5. Payment Terms Applicable to Paid Versions of the Minical Service</h3>
		<p>5.1. In order to register for or use a paid version of the Minical Service, you may be required to provide Minical with billing and account information (&quot;Billing Information&quot;) for a credit card, payment card or another payment system for which you are authorized to approve charges (each, a &quot;Payment Source&quot;) to allow Minical to collect payment from you for your use of the Minical Service. You must provide Minical with true, accurate, current and complete Billing Information and maintain and promptly update your Billing Information to keep it true, accurate, current and complete.</p>
		<p>5.2. You authorize Minical to automatically and immediately bill your Payment Source when charges for your use of the paid version of the Minical Service are due, without any further action on your part or other prior notice on the part of Minical. You assume full responsibility for such charges, even if such charges are declined or not paid by your Payment Source.</p>
		<p>5.3. If you register to use a paid version of the Minical Service on a free-trial basis and you do not cancel the trial before the expiration of the trial period, then, upon the expiration of the trial period, your account will be automatically converted to a paid account and your Payment Source will be billed for that paid Minical Service.</p>			
		<p>5.4. If your Payment Source is invalid, if charges billed to your Payment Source are declined or not paid or if you fail to pay charges for a paid version of the Minical Service when due, your account may be downgraded, suspended or cancelled, at Minical's discretion. If your account is suspended, Minical may, but is not obligated to, maintain your account and/or related content and information, in order to allow you pay the past-due charges and restore your account. If the charges are not paid, your account may be cancelled.</p>			
		<p>5.5. Unless stated to the contrary, all charges for paid versions of the Minical Service are non-refundable, even if your use of the paid version of the Minical Service is cancelled before the end of your current billing period.</p>			
		<p>5.6. Unless stated to the contrary, all currency references in paid versions of the Minical Service are in U.S. dollars (except in Canada where Canadian Dollars and applicable taxes are charged).</p>

		
		<h3>6. Additional Payment Terms Applicable to Minical Paid Plan Service Accounts</h3>			
		<p>6.1. If you subscribe to Minical Paid Plan Service on an annual basis, your payment of the Service Fee for the initial annual term is due on the Effective Date specified in your Minical Paid Plan upgrade screen. Payment of the Service Fee for each annual term thereafter is due in advance on the first day of each such annual term. Minical will invoice you for such Service Fees and you will pay each such invoice within thirty (30) days of its date.</p>
		<p>6.2. If you subscribe to Minical Paid Plan Service on a monthly basis, your payment of the Service Fee for the initial monthly term is due on the Effective Date specified in your Minical upgrade screen. Payment of the Service Fee for each monthly term thereafter is due in advance on the first day of each such monthly term. The Service Fee will be paid to Minical via your Payment Source. Minical will not initiate your Minical (paid) Service monthly subscription until Minical receives payment of the Service Fee for the initial monthly term in full.</p>
		<p>6.3. Minical reserves the right to audit and determine, in its sole discretion, whether the actual number of users in your Minical account in is in excess of the number of users specified in your Minical plan level. Minical's audit will be conclusive for the purposes of this determination. If Minical determines that the actual number of your Minical uses is in excess of the number of use specified in your Minical plan level, then:
		<ol>
		<li>If you subscribe to Minical Services on an annual basis, Minical may, in its sole discretion, (a) terminate your Minical Paid Plan account upon written notice to you or (b) invoice you the incremental Service Fee applicable to the actual number of your Minical Paid Plan Sites, retroactive to the date of creation of each such new Site and through and including the end of the then-current annual term. You will pay such invoice within thirty (30) days of its date. Your Minical Paid Plan account and annual Service Fee will be deemed amended effective on the date of Minical's invoice to reflect the actual number of your Minical Paid Plan Sites.</li>
		<li>If you subscribe to Minical Paid Plan Service on a monthly basis, Minical may, in its sole discretion, (a) terminate your Minical Paid Plan account upon written notice to you or (b) provide you with an amended credit or debit card payment authorization agreement for (b)(i) the incremental Service Fee applicable to the actual number of your Minical Paid Plan Sites, retroactive to the date of creation of each such new Site and through and including the end of the then-current monthly term and (b)(ii) the new Service Fee reflecting the actual number of your Minical Paid Plan Sites on a going-forward basis after the end of the then-current monthly term. You will execute and return such payment authorization agreement within fifteen (15) days of its date. Your Minical Paid Plan account and monthly Service Fee will be deemed amended effective on the date of the payment authorization agreement to reflect the actual number of your Minical Paid Plan Sites.</li>

		</ol>
		<p>6.4. If your account exceeds the maximum appointments/users/month specified in your Minical Paid Plan upgrade screen, Minical will notify you and you will be required to upgrade to maintain service.</p>			
		<p>6.5. Minical will invoice you for any Professional Services fees on a monthly basis and you will pay each such invoice no later than thirty (30) days after receipt.</p>
		<p>6.6. In addition to any other remedies available to Minical, you will pay a late fee of one and one-half percent (1.5%) per month (or the maximum amount permitted by law, whichever is less) for any late payments hereunder.</p>
		<p>6.7. As between you and Minical, you will, in addition to the other amounts payable to Minical, pay all sales and excise taxes and other taxes, federal, state, provincial, or otherwise, as well as customs duties where applicable, however designated, which are levied or imposed by reason of any transaction pursuant to this Minical Terms of Service, other than those taxes based on the income of Minical. You will pay to Minical an amount equal to any such taxes or duties actually paid, or required to be collected or paid, by Minical.</p>
		<p>6.8. If you are currently a customer of Magnuson Hotels, Magnuson Hotels will bill and process your payments under the Agreement – Terms and Conditions with Magnuson Hotels.</p>
		<h3>7. Upgrades and Downgrades</h3>
		<p>7.1. Minical may make available the ability for you to voluntarily upgrade or downgrade your account between free or paid versions and/or different service levels of the Minical Service. In addition, Minical reserves the right to downgrade your account if you fail to pay charges for a paid version of the Minical Service when due or if you cancel your account for a paid version of the Minical Service without requesting that Minical delete your account completely.</p>			
		<p>7.2. If your account is upgraded from a free version of the Minical Service to a paid version of the Minical Service, your Payment Source will be automatically billed for that paid Minical Service.</p>

		<p>7.3. If your account is upgraded to a service level of a paid version of the Minical Service for which the charges are greater than your current service level, your Payment Source will be automatically billed a the new amount due at the start of the next payment period.</p>		
		<p>7.4. If your account is downgraded from a paid version of the Minical Service to a free version of the Minical Service, or your account is downgraded to a service level of a paid version of the Minical Service for which the charges are less than your current service level, you will not receive a refund of the difference in the charges due for the balance of your current billing period.</p>
		<p>7.5. If your account is downgraded from a paid version of the Minical Service to which a discount is applied (including but not limited to a term or volume discount) to a paid version of the Minical Service to which a lesser or no discount is applied, Minical may bill your Payment Source to recover the amount of the difference in the charges due retroactive to the first date the discount was applied.</p>
		<p>7.6. Upgrading or downgrading your account between different versions or service levels of the Minical Service may result in changes to the features and functionality available to you. Further, downgrading your account may result in some or all of the content and information relating to your account being no longer available to you and/or being deleted by Minical. Minical will have no liability for content or information that is no longer available to you or that is deleted due to the downgrading of your account.</p>
		
		<h3>8. Content and Content Licenses</h3>			
		<p>8.1. Minical does not claim ownership over the content you post on the Minical Service. After posting your content, you continue to retain your ownership of your content and you continue to have the right to use and license your content in any way you choose. But by using the Minical Service or Minical's Web properties through which the Minical Service is available, you are granting Minical a nonexclusive, worldwide, royalty-free, sublicenseable and transferable right and license to use, reproduce, create derivative works of, distribute, publicly perform and publicly display your content, subject to any restrictions on such distribution which you may implement through any content distribution controls provided to you by Minical as part of the Minical Service. This license ends when you delete your content or your account (except to the extent that your content has been shared with others or syndicated to third parties and they have not deleted it). You may always decline to submit content to Minical, but please be aware that your decision may prevent you from being able to use all or portions of the Minical Service.</p>			
		<p>8.2. You acknowledge that Minical does not pre-screen content, but that Minical and its designees will have the right (but not the obligation) in their sole discretion to refuse or remove any content that is available via the Minical Service.</p>			
		<p>8.3. You will evaluate, and bear all risks associated with, the use of any content, including any reliance on the accuracy, completeness, or usefulness of such content and you understand that all content is the sole responsibility of the person from which such content originated. This means that you, and not Minical, are entirely responsible for all content that you upload, post, transmit or otherwise make available via the Minical Service. Minical does not control the content posted via the Minical Service and, as such, does not guarantee the accuracy, integrity or quality of such content.</p>

		<p>8.4. You understand that by using the Minical Service, you may be exposed to content that is offensive, indecent or objectionable. Under no circumstances will Minical be liable in any way for any content, including, but not limited to, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any content posted, transmitted or otherwise made available via the Minical Service.</p>			
		<p>8.5. Minical may preserve content and may also disclose content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce this TOS, the Terms of Use and the Minical Privacy Policy; (c) respond to claims that any content violates the rights of any third party; or (d) protect the rights, property, or personal safety of Minical, its users and the public.</p>
		<p>8.6. The technical processing and transmission of the Minical Service, including your content, may involve transmissions over various networks and changes to conform and adapt to technical requirements of connecting networks or devices.</p>

		
		<h3>9. Cancellation and Termination</h3>			
		<p>9.1. If you voluntarily cancel a paid version of the Minical Service before the end of your current billing period, your cancellation will take effect upon Minical's receipt and processing of your cancellation request.</p>			
		<p>9.2. Minical, in its sole discretion, may terminate your password and/or account and remove and discard any content within the Minical Service for any reason, including and without limitation lack of use, or if Minical believes that you have violated or acted inconsistently with the letter or spirit of this TOS, the Terms of Use or the Minical Privacy Policy. In such event, any contracts, verbal or written or assumed, in conjunction with your account and all its parts, at Minical's discretion, will be terminated as well.</p>			
		<p>9.3. Minical, in its sole discretion and at any time, may discontinue providing the Minical Service, or any part thereof, with or without notice. Any termination of your access to the Minical Service under any provision of this TOS may be effected without prior notice. Minical may immediately deactivate or delete your account, as applicable, and all related information and content. Minical reserves the right to bar any further access to such information or content or the Minical Service. Minical will not be liable to you or any third party for any termination of your access to the Minical Service.</p>			
		<p>9.4. After cancellation or termination of your account for any reason, you will no longer have access to your account and all information and content in your account or that you have stored on the Minical Service may be deleted by Minical. Minical will have no liability for information or content that is deleted due to the cancellation or termination of your account for any reason.</p>

		
		<h3>10. Additional Cancellation and Termination Terms Applicable to Minical Paid Plan Accounts</h3>
		<p>10.1. If you subscribe to Minical Paid Plan Service on an annual basis, your subscription will commence on the Effective Date specified in your Minical Paid Plan upgrade screen and will remain in full force and effect for an initial term of one (1) year, after which it will automatically renew for subsequent terms of one (1) year each unless terminated earlier by you or by Minical. You may terminate your Minical Paid Plan Service annual subscription only at the end of a full annual term, by giving Minical at least thirty (30) days advance written notice of such termination.</p>
		<p>10.2. If you subscribe to an Minical paid plan on a monthly basis, your subscription will commence on the Effective Date specified in your Minical Paid Plan upgrade screen and will remain in full force and effect for an initial term of one (1) month, after which it will automatically renew for subsequent terms of one (1) month each unless terminated earlier by you or by Minical. You may terminate your Minical paid plan monthly subscription by giving Minical at least ten (10) days advance written notice of such termination.</p>
		
		<h3>11. Additional Software</h3>
		<p>11.1. With respect to any additional software that may be made available by Minical in connection with the Minical Service, if you elect to download or access such additional software, you understand that you may have to agree to additional terms and conditions before you use such software.</p>
		
		<h3>12. Interstate and International Use</h3>

		<p>12.1. In using the Minical Service to send electronic communications, and as a result of Minical's network architecture and business practices and the nature of electronic communications in general, you acknowledge that your communications may constitute interstate or international communications and/or data transmissions regardless of where you are physically located at the time of transmission.</p>			
		<p>12.2. The Minical Service is hosted in the United States. If you use the Minical Service from outside of the United States, you are voluntarily transferring information (potentially including personally-identifiable information) and content to the United States and agreeing that Minical's collection, use, storage and sharing of your information and content is exclusively subject to the laws of the United States, not of the jurisdiction in which you are located.</p>			
		<p>12.3. You will comply with all Canadian and United States laws, rules and regulations applicable to the export of products, services, software and technical data regardless of the jurisdiction in which you are located.</p>
		
		<h3>13. Advertising and Advertisers</h3>			
		<p>13.1. The Minical Service may include advertisements, which are necessary for Minical to provide the Service. Minical reserves the right to include advertisements in different versions and/or in different service levels of the Minical Service at its discretion.</p>
		<p>13.2 Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Minical Service, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. Minical will not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Minical Service.</p>
		
		<h3>14. Links</h3>			
		<p>14.1. The Minical Service may provide, or third parties may provide, links to other content, products, services or Web sites which are not owned or operated by Minical. Because Minical has no control over such content, products, services or Web sties, Minical is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products, or other materials on or available from such sites or resources. Minical will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, products, services or Web sties.</p>
		
		<h3>15. Indemnity</h3>			
		<p>15.1. You will indemnify and hold Minical, and its subsidiaries, affiliates, officers, agents, co-branders or other partners, and employees, harmless from any claim or demand, including attorneys' fees on full indemnity basis, made by any third party due to or arising out of your content, your use of the Minical Service, your connection to the Minical Service, your violation of this TOS, the Terms of Use or the Minical Privacy Policy, or your violation of any rights of another, whether you are a registered user or not.</p>
		<p>15.2. You warrant and represent that accepting this TOS and Minical Service, the use of, Minical Service herein described or provided to you as additional services, do not, and will not result in the breach of or violate any terms, or result in default in any of your agreement with your franchise, or any other third party contracts. You take full responsibility for use of Minical Service or any other related services provided by Minical, and you will indemnify and save harmless, Minical and its subsidiaries, affiliates, officers, agents, co-branders or other partners, including its affiliated and associated entities or corporations and its respective insurers, heris, executors, administrators, employees, and successors and assigns, on a full indemnity basis including the Attorney-Client fees, of and from all action, actions, cause and causes of action, suits, sums of money, obligations, promises, contracts, common law claims, damages, costs or expenses, claims and demands of any and every kind in nature whatsoever, at law or in equity or otherwise, known or unknown, filed or not filed, due to or arising out of your content, your use of the Minical Service, your connection to the Minical Service, your violation of this TOS, the Terms of Use or the Minical Privacy Policy, or your violation of any rights of another, whether you are a registered user or an unregistered user.</p>

		<h3>16. Resale of Minical Service</h3>			
		<p>16.1. You will not reproduce, duplicate, copy, sell, resell or exploit any portion of the Minical Service, use of the Minical Service or access to the Minical Service without the express permission by Minical.</p>

		<h3>17. General Practices Regarding Use and Storage</h3>			
		<p>17.1. Minical may establish general practices and limits concerning use of the Minical Service and may modify such practices and limits from time to time.</p>
		
		<h3>18. Modifications to the Minical Service</h3>
		<p>18.1. Minical reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Minical Service (or any part thereof) with or without notice at any time. You agree that Minical will not be liable to you or to any third party for any modification, suspension or discontinuance of the Minical Service.</p>

		
		<h3>19. Confidential Information and Proprietary Rights</h3>			
		<p>19.1. The Minical Service and any necessary software used in connection with the Minical Service contains proprietary and confidential information that is protected by applicable intellectual property and other laws. content contained in sponsor advertisements or information presented to you through the Minical Service or advertisers may be protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly authorized by Minical or advertisers, you will not modify, rent, lease, loan, sell, distribute or create derivative works based on the Minical Service, any necessary software used in connection with the Minical Service or any advertiser's content, in whole or in part.</p>
		<p>19.2. Minical does not want to receive confidential or proprietary information from you through the Minical Service or by email. Unless otherwise agreed in writing by an authorized Minical representative, any material, information or idea you transmit to Minical by any means may be disseminated or used by Minical or its affiliates without compensation or liability to you for any purpose whatsoever, including, but not limited to, developing, manufacturing and marketing products. However, this provision does not apply to content or to your personal information that is subject to the Minical Privacy Policy.</p>
		
		<h3>20. Disclaimer of Warranties</h3>
		<p>20.1. <strong>You expressly understand and agree that:</strong>
		(a) Your use of the Minical Service is at your sole risk. The Minical Service is provided on an &quot;as is&quot; and &quot;as available&quot; basis. Minical expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose and non-infringement.
		(b) Minical will make reasonable efforts to maintain the Minical Service, however, Minical is not responsible for any damage, loss of data, customer information or vendor data, revenue, or other harm to business arising out of delays, misdelivery or nondelivery of information, restriction or loss of access, bugs or other errors, unauthorized use due to your sharing of access to the Minical Service, or other interaction with the Minical Service. You are responsible for maintaining and backing-up your data and information that may reside on the Minical Service. Minical does not warrant that (i) the Minical Service will meet your specific requirements, (ii) the Minical Service will be uninterrupted, timely, secure, or error-free, (iii) the results that may be obtained from the use of the Minical Service will be accurate or reliable, (iv) the quality of any products, services, information, or other material purchased or obtained by you through the Minical Service will meet your expectations, and (v) any errors in the Minical Service will be corrected.
		(c) Any material downloaded or otherwise obtained through the use of the Minical Service is done at your own discretion and risk. You will be solely responsible for any damage to your computer system or loss of data that results from the download of any such material.
		(d) No advice or information, whether oral or written, obtained through or from the Minical Service will create any warranty not expressly stated in this TOS.</p>

		
		<h3>21. Limitation of Liability</h3>			
		<p>21.1. You expressly understand and agree that Minical will not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if Minical has been advised of the possibility of such damages), resulting from: (i) the use or the inability to use the Minical Service; (ii) the cost of procurement of substitute goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the Minical Service; (iii) unauthorized access to or alteration of your transmissions or data; (iv) statements or conduct of any third party on the Minical Service; or (v) any other matter relating to the Minical Service.</p>
		
		<h3>22. Exclusions and Limitations</h3>			
		<p>22.1. Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of liability for incidental or consequential damages. Accordingly, some of the above limitations of sections 18 and 19 may not apply to you.</p>
		
		<h3>23. U.S. Government Restricted Rights</h3>
		<p>23.1. If you are an agency of the United States Government, the Minical Service is a &quot;Commercial Item,&quot; as that term is defined at 48 C.F.R. Section 2.101, consisting of &quot;Commercial Computer Software&quot; and &quot;Commercial Computer Software Documentation,&quot; as such terms are used in 48 C.F.R. Section 12.212 or 48 C.F.R. Section 227.7202, as applicable. Consistent with 48 C.F.R. Section 12.212 or 48 C.F.R. Section 227.7202-1 through 227.7202-4, as applicable, the Commercial Computer Software and Commercial Computer Software Documentation are being licensed to the United States Government (a) only as Commercial Items and (b) with only those rights as are granted to all other end users pursuant to the terms and conditions herein. All unpublished rights are reserved under the copyright laws of the United States. For purpose of any public disclosure provision under any law, it is agreed that the Minical Service is a trade secret and proprietary commercial product and not subject to disclosure.</p>

		
		<h3>24. General</h3>
		<p>24.1. Notices to you may be made via either email or regular mail. Minical may also provide notices of changes to this TOS or other matters by displaying notices or links to notices to you generally on the Minical Service.</p>
		<p>24.2. This TOS and the relationship between you and Minical will be governed by the laws of the Province of Alberta, Canada without regard to its conflict of law provisions. You and Minical agree to submit to the personal and exclusive jurisdiction of the courts located within Calgary, AB with regard to all disputes arising in any manner from the Minical Service, Minical's Web properties through which the Minical Service is available or this TOS.</p>			
		<p>24.3. The failure of Minical to exercise or enforce any right or provision of this TOS will not constitute a waiver of such right or provision. This TOS constitutes the entire agreement between you and Minical and governs your use of the Minical Service, superseding any prior agreements between you and Minical (including, but not limited to, any prior versions of this TOS). If any provision of this TOS or incorporated documents are found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavour to give effect to the parties' intentions as reflected in the provision, and the other provisions of this TOS will remain in full force and effect.</p>
		<p>24.4. You also may be subject to additional terms and conditions that may apply when you use affiliated or other Minical Services, third-party content or third-party software.</p>
		<p>24.5. Regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Minical Service, Minical's Web properties through which the Minical Service is available or this TOS must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>

		<p>24.6. The section titles in this TOS are for convenience only and have no legal or contractual effect.</p>			
		<p>Last updated on August 21st, 2015.</p>
	</div>
</div>
    </body>
</html>
